%Examples
#neg(eg(id0)@1, { kp(img) }, {  }, {

color(obj0,yellow).
color(obj1,purple).
color(obj2,brown).
color(obj3,gray).
color(obj5,cyan).
color(obj6,brown).
color(obj7,purple).
color(obj8,red).
color(obj9,yellow).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,rubber).
material(obj1,rubber).
material(obj2,rubber).
material(obj3,metal).
material(obj5,metal).
material(obj6,rubber).
material(obj7,rubber).
material(obj8,rubber).
material(obj9,rubber).
shape(obj0,sphere).
shape(obj1,cube).
shape(obj2,cube).
shape(obj3,cube).
shape(obj5,cylinder).
shape(obj6,cylinder).
shape(obj7,sphere).
shape(obj8,cube).
shape(obj9,sphere).
size(obj0,small).
size(obj1,small).
size(obj2,small).
size(obj3,large).
size(obj5,small).
size(obj6,large).
size(obj7,large).
size(obj8,small).
size(obj9,small).
}).
#neg(eg(id1)@1, { kp(img) }, {  }, {

color(obj0,brown).
color(obj5,gray).
color(obj7,blue).
color(obj8,green).
in(obj0,img).
in(obj5,img).
in(obj7,img).
in(obj8,img).
material(obj0,rubber).
material(obj5,rubber).
material(obj7,metal).
material(obj8,metal).
shape(obj0,sphere).
shape(obj5,cube).
shape(obj7,cylinder).
shape(obj8,sphere).
size(obj0,large).
size(obj5,large).
size(obj7,large).
size(obj8,small).
}).
#neg(eg(id2)@1, { kp(img) }, {  }, {

color(obj0,yellow).
color(obj1,brown).
color(obj2,red).
color(obj3,gray).
color(obj4,yellow).
color(obj5,cyan).
color(obj6,red).
color(obj8,purple).
color(obj9,blue).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj8,img).
in(obj9,img).
material(obj0,rubber).
material(obj1,metal).
material(obj2,rubber).
material(obj3,rubber).
material(obj4,rubber).
material(obj5,rubber).
material(obj6,metal).
material(obj8,metal).
material(obj9,rubber).
shape(obj0,sphere).
shape(obj1,cylinder).
shape(obj2,cube).
shape(obj3,cube).
shape(obj4,cylinder).
shape(obj5,cylinder).
shape(obj6,cylinder).
shape(obj8,sphere).
shape(obj9,cube).
size(obj0,small).
size(obj1,small).
size(obj2,small).
size(obj3,large).
size(obj4,large).
size(obj5,small).
size(obj6,small).
size(obj8,large).
size(obj9,small).
}).
#pos(eg(id3)@1, { kp(img) }, {  }, {

color(obj0,yellow).
color(obj2,purple).
color(obj3,yellow).
color(obj5,blue).
color(obj6,red).
color(obj8,purple).
in(obj0,img).
in(obj2,img).
in(obj3,img).
in(obj5,img).
in(obj6,img).
in(obj8,img).
material(obj0,rubber).
material(obj2,rubber).
material(obj3,rubber).
material(obj5,rubber).
material(obj6,rubber).
material(obj8,rubber).
shape(obj0,sphere).
shape(obj2,cube).
shape(obj3,cube).
shape(obj5,sphere).
shape(obj6,cylinder).
shape(obj8,cube).
size(obj0,small).
size(obj2,small).
size(obj3,small).
size(obj5,large).
size(obj6,large).
size(obj8,small).
}).
#neg(eg(id4)@1, { kp(img) }, {  }, {

color(obj0,green).
color(obj1,brown).
color(obj2,green).
color(obj3,gray).
color(obj4,yellow).
color(obj5,cyan).
color(obj6,green).
color(obj7,gray).
color(obj8,red).
color(obj9,purple).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,rubber).
material(obj1,metal).
material(obj2,rubber).
material(obj3,metal).
material(obj4,rubber).
material(obj5,rubber).
material(obj6,rubber).
material(obj7,rubber).
material(obj8,metal).
material(obj9,metal).
shape(obj0,cylinder).
shape(obj1,sphere).
shape(obj2,sphere).
shape(obj3,cube).
shape(obj4,cube).
shape(obj5,sphere).
shape(obj6,cube).
shape(obj7,sphere).
shape(obj8,cylinder).
shape(obj9,sphere).
size(obj0,large).
size(obj1,small).
size(obj2,small).
size(obj3,large).
size(obj4,small).
size(obj5,large).
size(obj6,small).
size(obj7,large).
size(obj8,small).
size(obj9,small).
}).
#pos(eg(id5)@1, { kp(img) }, {  }, {

color(obj0,yellow).
color(obj3,brown).
color(obj4,blue).
color(obj5,blue).
color(obj7,blue).
color(obj8,purple).
color(obj9,purple).
in(obj0,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,metal).
material(obj3,metal).
material(obj4,rubber).
material(obj5,metal).
material(obj7,rubber).
material(obj8,metal).
material(obj9,rubber).
shape(obj0,sphere).
shape(obj3,cylinder).
shape(obj4,cylinder).
shape(obj5,sphere).
shape(obj7,cylinder).
shape(obj8,sphere).
shape(obj9,sphere).
size(obj0,small).
size(obj2,small).
size(obj3,large).
size(obj4,large).
size(obj5,large).
size(obj7,large).
size(obj8,large).
size(obj9,small).
}).
#pos(eg(id6)@1, { kp(img) }, {  }, {

color(obj0,blue).
color(obj3,yellow).
color(obj5,cyan).
color(obj6,red).
in(obj0,img).
in(obj3,img).
in(obj5,img).
in(obj6,img).
material(obj0,rubber).
material(obj3,metal).
material(obj5,rubber).
material(obj6,rubber).
shape(obj0,sphere).
shape(obj3,sphere).
shape(obj5,cube).
shape(obj6,cube).
size(obj0,large).
size(obj3,small).
size(obj5,large).
size(obj6,small).
}).
#neg(eg(id7)@1, { kp(img) }, {  }, {

color(obj0,green).
color(obj1,yellow).
color(obj2,brown).
color(obj3,gray).
color(obj4,brown).
color(obj5,gray).
color(obj7,gray).
color(obj8,red).
color(obj9,red).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,rubber).
material(obj1,metal).
material(obj2,rubber).
material(obj3,metal).
material(obj4,rubber).
material(obj5,metal).
material(obj7,metal).
material(obj8,metal).
material(obj9,metal).
shape(obj0,sphere).
shape(obj1,cylinder).
shape(obj2,sphere).
shape(obj3,cylinder).
shape(obj4,cylinder).
shape(obj5,cube).
shape(obj7,cube).
shape(obj8,sphere).
shape(obj9,sphere).
size(obj0,small).
size(obj1,small).
size(obj2,small).
size(obj3,large).
size(obj4,small).
size(obj5,large).
size(obj7,large).
size(obj8,large).
size(obj9,small).
}).
#neg(eg(id8)@1, { kp(img) }, {  }, {

color(obj0,gray).
color(obj1,cyan).
color(obj3,gray).
color(obj5,cyan).
color(obj8,purple).
in(obj0,img).
in(obj1,img).
in(obj3,img).
in(obj5,img).
in(obj8,img).
material(obj0,rubber).
material(obj1,rubber).
material(obj3,metal).
material(obj5,rubber).
material(obj8,metal).
shape(obj0,cylinder).
shape(obj1,cylinder).
shape(obj3,cylinder).
shape(obj5,sphere).
shape(obj8,sphere).
size(obj0,large).
size(obj1,small).
size(obj3,small).
size(obj5,small).
size(obj8,small).
}).
#neg(eg(id9)@1, { kp(img) }, {  }, {

color(obj1,green).
color(obj2,green).
color(obj3,gray).
color(obj4,blue).
color(obj6,red).
color(obj8,purple).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj6,img).
in(obj8,img).
material(obj1,metal).
material(obj2,rubber).
material(obj3,rubber).
material(obj4,rubber).
material(obj6,rubber).
material(obj8,metal).
shape(obj1,cylinder).
shape(obj2,cylinder).
shape(obj3,cube).
shape(obj4,cylinder).
shape(obj6,cube).
shape(obj8,sphere).
size(obj1,small).
size(obj2,small).
size(obj3,large).
size(obj4,large).
size(obj6,small).
size(obj8,large).
}).
#neg(eg(id10)@1, { kp(img) }, {  }, {

color(obj0,green).
color(obj2,green).
color(obj3,gray).
color(obj4,blue).
color(obj5,cyan).
color(obj7,yellow).
color(obj8,red).
color(obj9,purple).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,rubber).
material(obj1,metal).
material(obj2,metal).
material(obj3,metal).
material(obj4,rubber).
material(obj5,rubber).
material(obj7,metal).
material(obj8,metal).
material(obj9,metal).
shape(obj0,sphere).
shape(obj1,cylinder).
shape(obj2,cylinder).
shape(obj3,cube).
shape(obj4,cylinder).
shape(obj5,cube).
shape(obj7,cylinder).
shape(obj8,sphere).
shape(obj9,sphere).
size(obj0,large).
size(obj1,small).
size(obj2,small).
size(obj3,large).
size(obj4,small).
size(obj5,small).
size(obj6,small).
size(obj7,large).
size(obj8,small).
size(obj9,small).
}).
#pos(eg(id11)@1, { kp(img) }, {  }, {

color(obj0,gray).
color(obj3,gray).
color(obj5,blue).
color(obj6,red).
color(obj7,red).
color(obj8,purple).
color(obj9,yellow).
in(obj0,img).
in(obj3,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,rubber).
material(obj3,rubber).
material(obj5,rubber).
material(obj6,rubber).
material(obj7,metal).
material(obj8,rubber).
material(obj9,metal).
shape(obj0,cube).
shape(obj3,sphere).
shape(obj5,sphere).
shape(obj6,sphere).
shape(obj7,cube).
shape(obj8,sphere).
shape(obj9,sphere).
size(obj0,large).
size(obj3,small).
size(obj5,large).
size(obj6,large).
size(obj7,large).
size(obj8,small).
size(obj9,small).
}).
#pos(eg(id12)@1, { kp(img) }, {  }, {

color(obj0,green).
color(obj3,yellow).
color(obj4,yellow).
color(obj5,cyan).
color(obj7,yellow).
color(obj8,red).
color(obj9,blue).
in(obj0,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,metal).
material(obj3,metal).
material(obj4,rubber).
material(obj5,rubber).
material(obj7,metal).
material(obj8,metal).
material(obj9,rubber).
shape(obj0,cylinder).
shape(obj3,sphere).
shape(obj4,cube).
shape(obj5,sphere).
shape(obj7,cylinder).
shape(obj8,cylinder).
shape(obj9,sphere).
size(obj0,large).
size(obj3,small).
size(obj4,small).
size(obj5,large).
size(obj7,large).
size(obj8,small).
size(obj9,large).
}).
#pos(eg(id13)@1, { kp(img) }, {  }, {

color(obj0,gray).
color(obj1,brown).
color(obj3,yellow).
color(obj4,purple).
color(obj5,blue).
color(obj6,purple).
color(obj8,red).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj8,img).
material(obj0,rubber).
material(obj1,metal).
material(obj2,rubber).
material(obj3,metal).
material(obj4,rubber).
material(obj5,metal).
material(obj6,rubber).
material(obj8,rubber).
shape(obj0,sphere).
shape(obj1,cylinder).
shape(obj3,sphere).
shape(obj4,cylinder).
shape(obj5,sphere).
shape(obj6,sphere).
shape(obj8,sphere).
size(obj0,small).
size(obj1,large).
size(obj2,small).
size(obj3,small).
size(obj4,small).
size(obj5,large).
size(obj6,large).
size(obj8,small).
}).
#neg(eg(id14)@1, { kp(img) }, {  }, {

color(obj0,brown).
color(obj2,red).
color(obj3,gray).
color(obj5,blue).
color(obj7,blue).
color(obj8,blue).
in(obj0,img).
in(obj2,img).
in(obj3,img).
in(obj5,img).
in(obj7,img).
in(obj8,img).
material(obj0,rubber).
material(obj2,rubber).
material(obj3,rubber).
material(obj5,metal).
material(obj7,rubber).
material(obj8,metal).
shape(obj0,cylinder).
shape(obj2,cylinder).
shape(obj3,cube).
shape(obj5,sphere).
shape(obj7,sphere).
shape(obj8,cylinder).
size(obj0,large).
size(obj2,small).
size(obj3,large).
size(obj5,large).
size(obj7,large).
size(obj8,small).
}).

% Background Knowledge

        
% Mode Declarations
            #constant(image,img).
            #constant(object,obj0).
            #constant(object,obj1).
            #constant(object,obj2).
            #constant(object,obj3).
            #constant(object,obj4).
            #constant(object,obj5).
            #constant(object,obj6).
            #constant(object,obj7).
            #constant(object,obj8).
            #constant(object,obj9).

            #constant(color,cyan).
            #constant(color,blue).
            #constant(color,yellow).
            #constant(color,purple).
            #constant(color,red).
            #constant(color,green).
            #constant(color,gray).
            #constant(color,brown).
            #constant(shape,sphere).
            #constant(shape,cube).
            #constant(shape,cylinder).
            #constant(material,rubber).
            #constant(material,metal).
            #modeh(kp(img)).
            #modeb(2, shape(var(object),const(shape))).
            #modeb(2, size(var(object),const(size))).
            #modeb(2, color(var(object),const(color))).