#neg(eg(id1)@1, { kp(img) }, {  }, {

color(obj0,yellow).
color(obj2,brown).
color(obj3,cyan).
color(obj7,gray).
color(obj8,yellow).
in(obj0,img).
in(obj2,img).
in(obj3,img).
in(obj7,img).
in(obj8,img).
material(obj0,metal).
material(obj2,metal).
material(obj3,metal).
material(obj7,metal).
material(obj8,rubber).
shape(obj0,cube).
shape(obj2,sphere).
shape(obj3,cube).
shape(obj7,sphere).
shape(obj8,sphere).
size(obj0,small).
size(obj2,small).
size(obj3,large).
size(obj7,large).
size(obj8,large).
}).
#neg(eg(id2)@1, { kp(img) }, {  }, {

color(obj2,brown).
color(obj3,green).
color(obj5,brown).
color(obj7,yellow).
color(obj8,blue).
in(obj2,img).
in(obj3,img).
in(obj5,img).
in(obj7,img).
in(obj8,img).
material(obj2,metal).
material(obj3,metal).
material(obj5,rubber).
material(obj7,metal).
material(obj8,rubber).
shape(obj2,cylinder).
shape(obj3,cube).
shape(obj5,sphere).
shape(obj7,sphere).
shape(obj8,sphere).
size(obj2,small).
size(obj3,large).
size(obj5,small).
size(obj7,small).
size(obj8,large).
}).
#neg(eg(id3)@1, { kp(img) }, {  }, {

color(obj2,yellow).
color(obj3,cyan).
color(obj4,purple).
color(obj5,red).
color(obj6,red).
color(obj7,blue).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
material(obj2,rubber).
material(obj3,rubber).
material(obj4,metal).
material(obj5,rubber).
material(obj6,rubber).
material(obj7,rubber).
shape(obj2,sphere).
shape(obj3,cube).
shape(obj4,cube).
shape(obj5,sphere).
shape(obj6,cube).
shape(obj7,sphere).
size(obj2,small).
size(obj3,large).
size(obj4,large).
size(obj5,small).
size(obj6,small).
size(obj7,large).
}).
#neg(eg(id4)@1, { kp(img) }, {  }, {

color(obj2,yellow).
color(obj4,yellow).
color(obj5,brown).
color(obj8,blue).
color(obj9,blue).
in(obj2,img).
in(obj4,img).
in(obj5,img).
in(obj8,img).
in(obj9,img).
material(obj2,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj8,rubber).
material(obj9,rubber).
shape(obj2,sphere).
shape(obj4,cube).
shape(obj5,sphere).
shape(obj8,sphere).
shape(obj9,cylinder).
size(obj2,small).
size(obj4,large).
size(obj5,small).
size(obj8,large).
size(obj9,small).
}).
#pos(eg(id5)@1, { kp(img) }, {  }, {

color(obj0,gray).
color(obj2,brown).
color(obj3,green).
color(obj4,blue).
color(obj5,red).
color(obj6,green).
color(obj7,gray).
color(obj9,purple).
in(obj0,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj9,img).
material(obj0,metal).
material(obj2,metal).
material(obj3,metal).
material(obj4,metal).
material(obj5,metal).
material(obj6,metal).
material(obj7,metal).
material(obj9,rubber).
shape(obj0,cube).
shape(obj2,sphere).
shape(obj3,cylinder).
shape(obj4,sphere).
shape(obj5,cube).
shape(obj6,cube).
shape(obj7,cylinder).
shape(obj9,cylinder).
size(obj0,small).
size(obj2,large).
size(obj3,large).
size(obj4,large).
size(obj5,small).
size(obj6,small).
size(obj7,large).
size(obj9,small).
}).
#pos(eg(id6)@1, { kp(img) }, {  }, {

color(obj0,gray).
color(obj2,brown).
color(obj3,cyan).
color(obj4,purple).
color(obj5,purple).
color(obj7,gray).
color(obj9,blue).
in(obj0,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj7,img).
in(obj9,img).
material(obj0,rubber).
material(obj2,metal).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj7,metal).
material(obj9,rubber).
shape(obj0,cube).
shape(obj2,sphere).
shape(obj3,sphere).
shape(obj4,cylinder).
shape(obj5,cylinder).
shape(obj7,sphere).
shape(obj9,cube).
size(obj0,large).
size(obj2,small).
size(obj3,small).
size(obj4,large).
size(obj5,small).
size(obj7,large).
size(obj9,small).
}).
#neg(eg(id7)@1, { kp(img) }, {  }, {

color(obj0,yellow).
color(obj1,yellow).
color(obj2,brown).
color(obj3,cyan).
color(obj4,blue).
color(obj5,purple).
color(obj7,blue).
color(obj9,blue).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,metal).
material(obj1,metal).
material(obj2,metal).
material(obj3,rubber).
material(obj4,metal).
material(obj5,rubber).
material(obj6,rubber).
material(obj7,rubber).
material(obj9,rubber).
shape(obj0,cylinder).
shape(obj1,cube).
shape(obj2,sphere).
shape(obj3,cylinder).
shape(obj4,cylinder).
shape(obj5,cube).
shape(obj7,sphere).
shape(obj9,cube).
size(obj0,small).
size(obj1,small).
size(obj2,small).
size(obj3,large).
size(obj4,large).
size(obj5,small).
size(obj6,small).
size(obj7,large).
size(obj8,small).
size(obj9,small).
}).
#pos(eg(id8)@1, { kp(img) }, {  }, {

color(obj5,blue).
color(obj6,green).
color(obj7,gray).
color(obj9,red).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj9,img).
material(obj5,rubber).
material(obj6,rubber).
material(obj7,metal).
material(obj9,rubber).
shape(obj5,cylinder).
shape(obj6,cylinder).
shape(obj7,cube).
shape(obj9,cylinder).
size(obj5,small).
size(obj6,small).
size(obj7,large).
size(obj9,large).
}).
#neg(eg(id9)@1, { kp(img) }, {  }, {

color(obj1,purple).
color(obj4,purple).
color(obj5,green).
in(obj1,img).
in(obj4,img).
in(obj5,img).
material(obj1,metal).
material(obj4,metal).
material(obj5,rubber).
shape(obj1,sphere).
shape(obj4,cube).
shape(obj5,cube).
size(obj1,small).
size(obj4,small).
size(obj5,small).
}).
#neg(eg(id10)@1, { kp(img) }, {  }, {

color(obj1,yellow).
color(obj2,green).
color(obj5,green).
color(obj7,blue).
color(obj8,blue).
in(obj1,img).
in(obj2,img).
in(obj5,img).
in(obj7,img).
in(obj8,img).
material(obj1,metal).
material(obj2,metal).
material(obj5,rubber).
material(obj7,rubber).
material(obj8,rubber).
shape(obj1,sphere).
shape(obj2,sphere).
shape(obj5,cube).
shape(obj7,sphere).
shape(obj8,sphere).
size(obj1,small).
size(obj2,large).
size(obj5,large).
size(obj7,large).
size(obj8,large).
}).
#neg(eg(id11)@1, { kp(img) }, {  }, {

color(obj0,blue).
color(obj1,red).
color(obj2,green).
color(obj3,green).
color(obj4,red).
color(obj6,yellow).
color(obj7,brown).
color(obj8,blue).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
material(obj0,rubber).
material(obj1,metal).
material(obj2,metal).
material(obj3,rubber).
material(obj4,metal).
material(obj6,metal).
material(obj7,rubber).
material(obj8,rubber).
shape(obj0,cylinder).
shape(obj1,cylinder).
shape(obj2,sphere).
shape(obj3,cube).
shape(obj4,cube).
shape(obj6,sphere).
shape(obj7,sphere).
shape(obj8,sphere).
size(obj0,small).
size(obj1,small).
size(obj2,large).
size(obj3,large).
size(obj4,large).
size(obj6,small).
size(obj7,large).
size(obj8,large).
}).
#neg(eg(id12)@1, { kp(img) }, {  }, {

color(obj0,yellow).
color(obj2,brown).
color(obj3,green).
color(obj4,purple).
color(obj5,purple).
color(obj7,brown).
color(obj8,yellow).
in(obj0,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj7,img).
in(obj8,img).
material(obj0,metal).
material(obj2,metal).
material(obj3,rubber).
material(obj4,metal).
material(obj5,rubber).
material(obj7,rubber).
material(obj8,rubber).
shape(obj0,cube).
shape(obj2,sphere).
shape(obj3,sphere).
shape(obj4,cube).
shape(obj5,cylinder).
shape(obj7,sphere).
shape(obj8,sphere).
size(obj0,large).
size(obj2,small).
size(obj3,large).
size(obj4,small).
size(obj5,small).
size(obj7,large).
size(obj8,large).
}).
#neg(eg(id13)@1, { kp(img) }, {  }, {

color(obj0,blue).
color(obj0,yellow).
color(obj1,purple).
color(obj2,green).
color(obj3,blue).
color(obj4,blue).
color(obj5,purple).
color(obj6,gray).
color(obj7,yellow).
color(obj8,cyan).
color(obj9,blue).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,metal).
material(obj1,metal).
material(obj2,metal).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj6,metal).
material(obj7,metal).
material(obj8,rubber).
material(obj9,rubber).
shape(obj0,cylinder).
shape(obj1,sphere).
shape(obj2,sphere).
shape(obj3,cube).
shape(obj4,cylinder).
shape(obj5,cylinder).
shape(obj6,cylinder).
shape(obj7,cylinder).
shape(obj8,cube).
shape(obj9,cylinder).
size(obj0,small).
size(obj1,small).
size(obj2,large).
size(obj3,small).
size(obj4,large).
size(obj5,large).
size(obj6,small).
size(obj7,small).
size(obj8,small).
size(obj9,small).
}).
#pos(eg(id14)@1, { kp(img) }, {  }, {

color(obj0,brown).
color(obj1,blue).
color(obj3,green).
color(obj5,green).
color(obj6,purple).
color(obj7,gray).
color(obj8,yellow).
in(obj0,img).
in(obj1,img).
in(obj3,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,rubber).
material(obj1,metal).
material(obj3,metal).
material(obj5,rubber).
material(obj6,rubber).
material(obj7,metal).
material(obj8,rubber).
material(obj9,rubber).
shape(obj0,cylinder).
shape(obj1,cylinder).
shape(obj3,cylinder).
shape(obj5,sphere).
shape(obj6,sphere).
shape(obj7,cube).
shape(obj8,sphere).
shape(obj9,sphere).
size(obj0,large).
size(obj1,small).
size(obj3,small).
size(obj5,small).
size(obj6,large).
size(obj7,large).
size(obj8,small).
size(obj9,large).
}).
#neg(eg(id15)@1, { kp(img) }, {  }, {

color(obj2,brown).
color(obj3,green).
color(obj4,red).
color(obj5,gray).
color(obj7,yellow).
color(obj8,gray).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj7,img).
in(obj8,img).
material(obj2,metal).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj7,metal).
material(obj8,rubber).
shape(obj2,cube).
shape(obj3,cylinder).
shape(obj4,sphere).
shape(obj5,cylinder).
shape(obj7,sphere).
shape(obj8,cube).
size(obj2,small).
size(obj3,small).
size(obj4,large).
size(obj5,small).
size(obj7,small).
size(obj8,small).
}).
#neg(eg(id16)@1, { kp(img) }, {  }, {

color(obj1,red).
color(obj3,gray).
color(obj5,purple).
in(obj1,img).
in(obj3,img).
in(obj5,img).
material(obj1,metal).
material(obj3,metal).
material(obj5,rubber).
shape(obj1,sphere).
shape(obj3,cube).
shape(obj5,sphere).
size(obj1,small).
size(obj3,small).
size(obj5,large).
}).
#neg(eg(id17)@1, { kp(img) }, {  }, {

color(obj1,red).
color(obj3,gray).
color(obj4,red).
color(obj5,red).
in(obj1,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
material(obj1,metal).
material(obj3,metal).
material(obj4,metal).
material(obj5,metal).
shape(obj1,sphere).
shape(obj3,cube).
shape(obj4,cylinder).
shape(obj5,cylinder).
size(obj1,small).
size(obj3,small).
size(obj4,large).
size(obj5,small).
}).
#neg(eg(id18)@1, { kp(img) }, {  }, {

color(obj0,brown).
color(obj1,red).
color(obj2,yellow).
color(obj3,blue).
color(obj4,red).
color(obj5,blue).
color(obj6,brown).
color(obj7,gray).
color(obj9,red).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj9,img).
material(obj0,rubber).
material(obj1,metal).
material(obj2,metal).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj6,rubber).
material(obj7,rubber).
material(obj9,rubber).
shape(obj0,cylinder).
shape(obj1,sphere).
shape(obj2,cube).
shape(obj3,cylinder).
shape(obj4,sphere).
shape(obj5,cylinder).
shape(obj6,cylinder).
shape(obj7,cube).
shape(obj9,cylinder).
size(obj0,large).
size(obj1,small).
size(obj2,small).
size(obj3,small).
size(obj4,large).
size(obj5,large).
size(obj6,large).
size(obj7,small).
size(obj9,large).
}).
#pos(eg(id19)@1, { kp(img) }, {  }, {

color(obj0,gray).
color(obj3,gray).
color(obj4,purple).
color(obj5,green).
color(obj7,gray).
in(obj0,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj7,img).
material(obj0,rubber).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj7,rubber).
shape(obj0,cube).
shape(obj3,cube).
shape(obj4,cylinder).
shape(obj5,cylinder).
shape(obj7,sphere).
size(obj0,large).
size(obj3,small).
size(obj4,large).
size(obj5,small).
size(obj7,large).
}).
#neg(eg(id20)@1, { kp(img) }, {  }, {

color(obj2,gray).
color(obj3,cyan).
color(obj4,red).
color(obj5,red).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
material(obj2,metal).
material(obj3,metal).
material(obj4,metal).
shape(obj2,sphere).
shape(obj3,cube).
shape(obj4,cylinder).
size(obj2,small).
size(obj3,small).
size(obj4,large).
}).
#pos(eg(id21)@1, { kp(img) }, {  }, {

color(obj0,yellow).
color(obj3,cyan).
color(obj4,purple).
color(obj5,red).
color(obj6,brown).
color(obj7,brown).
color(obj8,gray).
color(obj9,blue).
in(obj0,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,rubber).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj6,rubber).
material(obj7,rubber).
material(obj8,rubber).
material(obj9,rubber).
shape(obj0,cylinder).
shape(obj3,cube).
shape(obj4,cube).
shape(obj5,cylinder).
shape(obj6,sphere).
shape(obj7,sphere).
shape(obj8,cube).
shape(obj9,cylinder).
size(obj0,large).
size(obj3,small).
size(obj4,small).
size(obj5,small).
size(obj6,large).
size(obj7,large).
size(obj8,large).
size(obj9,small).
}).
#neg(eg(id22)@1, { kp(img) }, {  }, {

color(obj0,cyan).
color(obj2,green).
color(obj5,green).
in(obj0,img).
in(obj2,img).
in(obj5,img).
material(obj0,metal).
material(obj2,metal).
material(obj5,rubber).
shape(obj0,cube).
shape(obj2,sphere).
shape(obj5,cube).
size(obj0,small).
size(obj2,small).
size(obj5,small).
}).
#pos(eg(id23)@1, { kp(img) }, {  }, {

color(obj0,gray).
color(obj1,cyan).
color(obj2,green).
color(obj3,cyan).
color(obj4,red).
color(obj5,blue).
color(obj6,gray).
color(obj7,blue).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
material(obj0,rubber).
material(obj1,metal).
material(obj2,metal).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj6,rubber).
material(obj7,rubber).
shape(obj0,cube).
shape(obj1,cube).
shape(obj2,sphere).
shape(obj3,sphere).
shape(obj4,cylinder).
shape(obj5,cylinder).
shape(obj6,cylinder).
shape(obj7,sphere).
size(obj0,large).
size(obj1,small).
size(obj2,large).
size(obj3,large).
size(obj4,large).
size(obj5,small).
size(obj6,small).
size(obj7,large).
}).
#neg(eg(id24)@1, { kp(img) }, {  }, {

color(obj4,blue).
color(obj5,yellow).
color(obj7,blue).
in(obj4,img).
in(obj5,img).
in(obj7,img).
material(obj4,metal).
material(obj5,rubber).
material(obj7,rubber).
shape(obj4,cylinder).
shape(obj5,sphere).
shape(obj7,sphere).
size(obj4,large).
size(obj5,small).
size(obj7,large).
}).
#pos(eg(id25)@1, { kp(img) }, {  }, {

color(obj0,brown).
color(obj1,cyan).
color(obj3,cyan).
color(obj4,blue).
color(obj5,green).
color(obj7,gray).
color(obj9,brown).
in(obj0,img).
in(obj1,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj7,img).
in(obj9,img).
material(obj0,rubber).
material(obj1,metal).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj7,rubber).
material(obj9,rubber).
shape(obj0,cylinder).
shape(obj1,cube).
shape(obj3,sphere).
shape(obj4,cylinder).
shape(obj5,cube).
shape(obj7,cube).
shape(obj9,cube).
size(obj0,large).
size(obj1,small).
size(obj3,large).
size(obj4,small).
size(obj5,small).
size(obj7,large).
size(obj9,small).
}).
#pos(eg(id26)@1, { kp(img) }, {  }, {

color(obj0,blue).
color(obj1,green).
color(obj3,green).
color(obj5,red).
color(obj6,cyan).
color(obj7,gray).
color(obj9,yellow).
in(obj0,img).
in(obj1,img).
in(obj3,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj9,img).
material(obj0,rubber).
material(obj1,rubber).
material(obj3,metal).
material(obj5,rubber).
material(obj6,metal).
material(obj7,metal).
material(obj9,rubber).
shape(obj0,cylinder).
shape(obj1,sphere).
shape(obj3,sphere).
shape(obj5,sphere).
shape(obj6,cube).
shape(obj7,cube).
shape(obj9,cube).
size(obj0,large).
size(obj1,small).
size(obj3,small).
size(obj5,small).
size(obj6,small).
size(obj7,large).
size(obj9,small).
}).
#neg(eg(id27)@1, { kp(img) }, {  }, {

color(obj0,yellow).
color(obj1,purple).
color(obj2,yellow).
color(obj3,cyan).
color(obj4,blue).
color(obj5,yellow).
color(obj6,brown).
color(obj7,blue).
color(obj8,gray).
color(obj9,red).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,metal).
material(obj1,metal).
material(obj2,metal).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj6,rubber).
material(obj7,rubber).
material(obj8,rubber).
material(obj9,rubber).
shape(obj0,cylinder).
shape(obj1,sphere).
shape(obj2,sphere).
shape(obj3,cylinder).
shape(obj4,cylinder).
shape(obj5,cube).
shape(obj6,sphere).
shape(obj7,sphere).
shape(obj8,cube).
shape(obj9,cube).
size(obj0,small).
size(obj1,small).
size(obj2,small).
size(obj3,small).
size(obj4,small).
size(obj5,small).
size(obj6,small).
size(obj7,large).
size(obj8,small).
size(obj9,large).
}).
#neg(eg(id28)@1, { kp(img) }, {  }, {

color(obj0,green).
color(obj1,blue).
color(obj2,green).
color(obj3,green).
color(obj4,cyan).
color(obj5,green).
color(obj6,green).
color(obj7,gray).
color(obj8,red).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,metal).
material(obj1,metal).
material(obj2,rubber).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj6,metal).
material(obj7,rubber).
material(obj8,rubber).
material(obj9,rubber).
shape(obj0,cylinder).
shape(obj1,sphere).
shape(obj3,cylinder).
shape(obj4,cylinder).
shape(obj5,cylinder).
shape(obj6,cylinder).
shape(obj7,sphere).
shape(obj8,cylinder).
size(obj0,small).
size(obj1,large).
size(obj2,small).
size(obj3,large).
size(obj4,large).
size(obj5,small).
size(obj6,small).
size(obj7,small).
size(obj8,small).
size(obj9,small).
}).
#pos(eg(id29)@1, { kp(img) }, {  }, {

color(obj0,gray).
color(obj3,gray).
color(obj4,purple).
color(obj5,yellow).
color(obj7,yellow).
in(obj0,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj7,img).
material(obj0,rubber).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj7,metal).
shape(obj0,cube).
shape(obj3,cube).
shape(obj4,sphere).
shape(obj5,cylinder).
shape(obj7,cylinder).
size(obj0,large).
size(obj3,small).
size(obj4,large).
size(obj5,small).
size(obj7,large).
}).

% Background Knowledge

        
% Mode Declarations
            #constant(image,img).
            #constant(object,obj0).
            #constant(object,obj1).
            #constant(object,obj2).
            #constant(object,obj3).
            #constant(object,obj4).
            #constant(object,obj5).
            #constant(object,obj6).
            #constant(object,obj7).
            #constant(object,obj8).
            #constant(object,obj9).

            #constant(color,cyan).
            #constant(color,blue).
            #constant(color,yellow).
            #constant(color,purple).
            #constant(color,red).
            #constant(color,green).
            #constant(color,gray).
            #constant(color,brown).
            #constant(shape,sphere).
            #constant(shape,cube).
            #constant(shape,cylinder).
            #constant(material,rubber).
            #constant(material,metal).
            #constant(size,large).
            #constant(size,small).

            #modeh(kp(img)).
            #modeb(2, in(var(object,var(image)))).
            #modeb(2, shape(var(object),const(shape))).
            #modeb(2, size(var(object),const(size))).
            % #modeb(2, material(var(object),const(material))).
            % #modeb(2, color(var(object),const(color))).