%Examples
#neg({kp(img)}, {}, {

color(obj1,purple).
color(obj2,green).
color(obj3,blue).
color(obj4,gray).
color(obj5,blue).
color(obj6,yellow).
color(obj7,brown).
color(obj9,yellow).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj9,img).
material(obj1,metal).
material(obj2,metal).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj6,metal).
material(obj7,metal).
material(obj9,metal).
shape(obj1,cylinder).
shape(obj2,sphere).
shape(obj3,sphere).
shape(obj4,sphere).
shape(obj5,cylinder).
shape(obj6,sphere).
shape(obj7,cylinder).
shape(obj9,sphere).
size(obj1,large).
size(obj2,large).
size(obj3,large).
size(obj4,large).
size(obj5,small).
size(obj6,small).
size(obj7,large).
size(obj9,large).
}).
#neg({kp(img)}, {}, {

color(obj1,purple).
color(obj3,gray).
color(obj4,brown).
color(obj5,cyan).
in(obj1,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
material(obj1,metal).
material(obj3,metal).
material(obj4,metal).
material(obj5,metal).
shape(obj1,cube).
shape(obj3,cube).
shape(obj4,sphere).
shape(obj5,cube).
size(obj1,large).
size(obj3,small).
size(obj4,small).
size(obj5,large).
}).
#neg({kp(img)}, {}, {

color(obj0,green).
color(obj4,cyan).
color(obj7,red).
in(obj0,img).
in(obj4,img).
in(obj7,img).
material(obj0,rubber).
material(obj4,metal).
material(obj7,metal).
shape(obj0,sphere).
shape(obj4,sphere).
shape(obj7,cube).
size(obj0,large).
size(obj4,small).
size(obj7,small).
}).
#neg({kp(img)}, {}, {

color(obj0,red).
color(obj2,purple).
color(obj3,cyan).
color(obj4,cyan).
color(obj5,purple).
color(obj6,blue).
color(obj7,red).
color(obj8,blue).
color(obj9,yellow).
in(obj0,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,rubber).
material(obj2,metal).
material(obj3,rubber).
material(obj4,metal).
material(obj5,rubber).
material(obj6,rubber).
material(obj7,rubber).
material(obj8,rubber).
material(obj9,rubber).
shape(obj0,cylinder).
shape(obj2,cube).
shape(obj3,sphere).
shape(obj4,sphere).
shape(obj5,cube).
shape(obj6,sphere).
shape(obj7,sphere).
shape(obj8,cylinder).
shape(obj9,sphere).
size(obj0,small).
size(obj2,large).
size(obj3,small).
size(obj4,large).
size(obj5,large).
size(obj6,large).
size(obj7,small).
size(obj8,small).
size(obj9,small).
}).
#neg({kp(img)}, {}, {

color(obj2,red).
color(obj4,blue).
color(obj5,brown).
color(obj6,green).
color(obj7,purple).
color(obj9,yellow).
in(obj2,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj9,img).
material(obj2,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj6,metal).
material(obj7,metal).
material(obj9,metal).
shape(obj2,cylinder).
shape(obj4,sphere).
shape(obj5,cylinder).
shape(obj6,cylinder).
shape(obj7,cube).
shape(obj9,cylinder).
size(obj2,large).
size(obj4,small).
size(obj5,large).
size(obj6,large).
size(obj7,small).
size(obj9,small).
}).
#neg({kp(img)}, {}, {

color(obj1,red).
color(obj2,blue).
color(obj5,cyan).
color(obj6,gray).
color(obj8,blue).
color(obj9,yellow).
in(obj1,img).
in(obj2,img).
in(obj5,img).
in(obj6,img).
in(obj8,img).
in(obj9,img).
material(obj1,rubber).
material(obj2,metal).
material(obj5,rubber).
material(obj6,rubber).
material(obj8,rubber).
material(obj9,rubber).
shape(obj1,cube).
shape(obj2,sphere).
shape(obj5,cube).
shape(obj6,sphere).
shape(obj8,cube).
shape(obj9,sphere).
size(obj1,large).
size(obj2,large).
size(obj5,large).
size(obj6,small).
size(obj8,small).
size(obj9,small).
}).
#pos({kp(img)}, {}, {

color(obj0,brown).
color(obj1,green).
color(obj2,yellow).
color(obj3,purple).
color(obj4,red).
color(obj5,gray).
color(obj7,brown).
color(obj9,purple).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj7,img).
in(obj9,img).
material(obj0,rubber).
material(obj1,rubber).
material(obj2,metal).
material(obj3,rubber).
material(obj4,metal).
material(obj5,rubber).
material(obj7,metal).
material(obj9,metal).
shape(obj0,sphere).
shape(obj1,cube).
shape(obj2,cylinder).
shape(obj3,sphere).
shape(obj4,cylinder).
shape(obj5,cube).
shape(obj7,cylinder).
shape(obj9,sphere).
size(obj0,small).
size(obj1,small).
size(obj2,large).
size(obj3,small).
size(obj4,small).
size(obj5,large).
size(obj7,small).
size(obj9,small).
}).
#neg({kp(img)}, {}, {

color(obj2,yellow).
color(obj3,cyan).
color(obj4,green).
color(obj6,gray).
color(obj8,cyan).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj6,img).
in(obj8,img).
material(obj2,metal).
material(obj3,metal).
material(obj4,metal).
material(obj6,rubber).
material(obj8,rubber).
shape(obj2,sphere).
shape(obj3,cube).
shape(obj4,sphere).
shape(obj6,cylinder).
shape(obj8,cylinder).
size(obj2,large).
size(obj3,small).
size(obj4,small).
size(obj6,large).
size(obj8,large).
}).
#pos({kp(img)}, {}, {

color(obj0,purple).
color(obj1,yellow).
color(obj2,purple).
color(obj3,purple).
color(obj4,cyan).
color(obj5,brown).
color(obj6,gray).
color(obj7,red).
color(obj8,blue).
color(obj9,yellow).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,rubber).
material(obj1,rubber).
material(obj2,metal).
material(obj3,rubber).
material(obj4,rubber).
material(obj5,rubber).
material(obj6,rubber).
material(obj7,metal).
material(obj8,rubber).
material(obj9,metal).
shape(obj0,cylinder).
shape(obj1,cylinder).
shape(obj2,cube).
shape(obj3,cylinder).
shape(obj4,cube).
shape(obj5,sphere).
shape(obj6,cube).
shape(obj7,cube).
shape(obj8,cylinder).
shape(obj9,cube).
size(obj0,small).
size(obj1,large).
size(obj2,small).
size(obj3,small).
size(obj4,small).
size(obj5,large).
size(obj6,large).
size(obj7,small).
size(obj8,small).
size(obj9,small).
}).
#pos({kp(img)}, {}, {

color(obj1,gray).
color(obj2,green).
color(obj3,blue).
color(obj4,brown).
color(obj5,gray).
color(obj6,cyan).
color(obj7,yellow).
color(obj8,cyan).
color(obj9,yellow).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj1,rubber).
material(obj2,metal).
material(obj3,rubber).
material(obj4,metal).
material(obj5,rubber).
material(obj6,rubber).
material(obj7,metal).
material(obj8,rubber).
material(obj9,metal).
shape(obj1,cylinder).
shape(obj2,sphere).
shape(obj3,cylinder).
shape(obj4,sphere).
shape(obj5,cube).
shape(obj6,sphere).
shape(obj7,cylinder).
shape(obj8,cylinder).
shape(obj9,sphere).
size(obj1,small).
size(obj2,large).
size(obj3,small).
size(obj4,small).
size(obj5,large).
size(obj6,large).
size(obj7,large).
size(obj8,small).
size(obj9,small).
}).
#neg({kp(img)}, {}, {

color(obj0,purple).
color(obj1,yellow).
color(obj2,blue).
color(obj4,cyan).
color(obj5,yellow).
color(obj6,gray).
color(obj8,cyan).
color(obj9,yellow).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj8,img).
in(obj9,img).
material(obj0,rubber).
material(obj1,rubber).
material(obj2,metal).
material(obj4,rubber).
material(obj5,metal).
material(obj6,rubber).
material(obj8,metal).
material(obj9,metal).
shape(obj0,cube).
shape(obj1,cylinder).
shape(obj2,sphere).
shape(obj4,sphere).
shape(obj5,sphere).
shape(obj6,sphere).
shape(obj8,cylinder).
shape(obj9,sphere).
size(obj0,small).
size(obj1,large).
size(obj2,large).
size(obj4,small).
size(obj5,small).
size(obj6,large).
size(obj8,large).
size(obj9,large).
}).
#pos({kp(img)}, {}, {

color(obj2,cyan).
color(obj3,cyan).
color(obj4,gray).
color(obj5,gray).
color(obj7,red).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj7,img).
material(obj2,metal).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj7,metal).
shape(obj2,cylinder).
shape(obj3,cylinder).
shape(obj4,sphere).
shape(obj5,cube).
shape(obj7,cylinder).
size(obj2,large).
size(obj3,small).
size(obj4,small).
size(obj5,large).
size(obj7,small).
}).
#neg({kp(img)}, {}, {

color(obj0,purple).
color(obj2,yellow).
color(obj3,gray).
color(obj5,blue).
color(obj7,red).
color(obj8,yellow).
color(obj9,yellow).
in(obj0,img).
in(obj2,img).
in(obj3,img).
in(obj5,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,rubber).
material(obj2,metal).
material(obj3,metal).
material(obj5,rubber).
material(obj7,metal).
material(obj8,rubber).
material(obj9,rubber).
shape(obj0,sphere).
shape(obj2,sphere).
shape(obj3,cylinder).
shape(obj5,sphere).
shape(obj7,sphere).
shape(obj8,sphere).
shape(obj9,cylinder).
size(obj0,large).
size(obj2,large).
size(obj3,large).
size(obj5,large).
size(obj7,small).
size(obj8,small).
size(obj9,small).
}).
#pos({kp(img)}, {}, {

color(obj0,brown).
color(obj1,green).
color(obj2,blue).
color(obj3,blue).
color(obj4,gray).
color(obj5,purple).
color(obj6,cyan).
color(obj7,gray).
color(obj8,gray).
color(obj9,yellow).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,rubber).
material(obj1,rubber).
material(obj2,metal).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj6,metal).
material(obj7,metal).
material(obj8,metal).
material(obj9,metal).
shape(obj0,sphere).
shape(obj1,sphere).
shape(obj2,cylinder).
shape(obj3,cylinder).
shape(obj4,sphere).
shape(obj5,sphere).
shape(obj6,sphere).
shape(obj7,cylinder).
shape(obj8,cube).
shape(obj9,sphere).
size(obj0,small).
size(obj1,small).
size(obj2,large).
size(obj3,small).
size(obj4,large).
size(obj5,large).
size(obj6,small).
size(obj7,small).
size(obj8,large).
size(obj9,small).
}).
#pos({kp(img)}, {}, {

color(obj2,red).
color(obj5,gray).
color(obj7,brown).
color(obj9,yellow).
in(obj2,img).
in(obj5,img).
in(obj7,img).
in(obj9,img).
material(obj2,metal).
material(obj5,rubber).
material(obj7,metal).
material(obj9,rubber).
shape(obj2,cylinder).
shape(obj5,cube).
shape(obj7,cylinder).
shape(obj9,cylinder).
size(obj2,large).
size(obj5,large).
size(obj7,small).
size(obj9,small).
}).
#neg({kp(img)}, {}, {

color(obj0,red).
color(obj2,blue).
color(obj3,purple).
color(obj7,red).
color(obj9,yellow).
in(obj0,img).
in(obj2,img).
in(obj3,img).
in(obj7,img).
in(obj9,img).
material(obj0,rubber).
material(obj2,metal).
material(obj3,metal).
material(obj7,rubber).
material(obj9,metal).
shape(obj0,sphere).
shape(obj2,sphere).
shape(obj3,sphere).
shape(obj7,cylinder).
shape(obj9,sphere).
size(obj0,small).
size(obj2,large).
size(obj3,small).
size(obj7,small).
size(obj9,small).
}).
#neg({kp(img)}, {}, {

color(obj0,green).
color(obj2,blue).
color(obj4,blue).
color(obj6,blue).
color(obj7,purple).
color(obj9,yellow).
in(obj0,img).
in(obj2,img).
in(obj4,img).
in(obj6,img).
in(obj7,img).
in(obj9,img).
material(obj0,rubber).
material(obj2,metal).
material(obj4,metal).
material(obj6,rubber).
material(obj7,rubber).
material(obj9,rubber).
shape(obj0,cube).
shape(obj2,cylinder).
shape(obj4,sphere).
shape(obj6,sphere).
shape(obj7,cube).
shape(obj9,sphere).
size(obj0,small).
size(obj2,small).
size(obj4,small).
size(obj6,large).
size(obj7,small).
size(obj9,small).
}).
#neg({kp(img)}, {}, {

color(obj1,yellow).
color(obj2,blue).
color(obj3,blue).
color(obj4,gray).
color(obj5,purple).
color(obj6,yellow).
color(obj7,red).
color(obj9,yellow).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj9,img).
material(obj1,rubber).
material(obj2,metal).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj6,rubber).
material(obj7,metal).
material(obj9,metal).
shape(obj1,cube).
shape(obj2,cylinder).
shape(obj3,cube).
shape(obj4,cylinder).
shape(obj5,cube).
shape(obj6,cube).
shape(obj7,sphere).
shape(obj9,cylinder).
size(obj1,large).
size(obj2,small).
size(obj3,small).
size(obj4,small).
size(obj5,large).
size(obj6,small).
size(obj7,small).
size(obj9,small).
}).
#neg({kp(img)}, {}, {

color(obj0,brown).
color(obj2,gray).
color(obj3,blue).
color(obj4,green).
color(obj5,gray).
color(obj6,yellow).
color(obj7,red).
in(obj0,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
material(obj0,rubber).
material(obj2,metal).
material(obj3,metal).
material(obj4,rubber).
material(obj5,rubber).
material(obj6,rubber).
material(obj7,rubber).
shape(obj0,sphere).
shape(obj2,cube).
shape(obj3,sphere).
shape(obj4,sphere).
shape(obj5,cube).
shape(obj6,sphere).
shape(obj7,cylinder).
size(obj0,large).
size(obj2,large).
size(obj3,large).
size(obj4,large).
size(obj5,large).
size(obj6,small).
size(obj7,small).
}).
#neg({kp(img)}, {}, {

color(obj0,green).
color(obj2,blue).
color(obj3,green).
color(obj4,green).
color(obj7,green).
in(obj0,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj7,img).
material(obj0,rubber).
material(obj2,metal).
material(obj3,rubber).
material(obj4,metal).
material(obj7,metal).
shape(obj0,cylinder).
shape(obj2,cylinder).
shape(obj3,cube).
shape(obj4,sphere).
shape(obj7,cube).
size(obj0,small).
size(obj2,large).
size(obj3,small).
size(obj4,small).
size(obj7,small).
}).
#neg({kp(img)}, {}, {

color(obj2,blue).
color(obj4,cyan).
color(obj9,yellow).
in(obj2,img).
in(obj4,img).
in(obj9,img).
material(obj2,metal).
material(obj4,metal).
material(obj9,metal).
shape(obj2,sphere).
shape(obj4,sphere).
shape(obj9,sphere).
size(obj2,large).
size(obj4,small).
size(obj9,small).
}).
#neg({kp(img)}, {}, {

color(obj0,green).
color(obj2,yellow).
color(obj3,blue).
color(obj4,purple).
color(obj5,gray).
color(obj6,cyan).
color(obj7,brown).
color(obj8,brown).
color(obj9,yellow).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,rubber).
material(obj1,rubber).
material(obj2,metal).
material(obj3,rubber).
material(obj4,metal).
material(obj5,rubber).
material(obj6,rubber).
material(obj7,metal).
material(obj8,rubber).
material(obj9,rubber).
shape(obj0,sphere).
shape(obj2,cylinder).
shape(obj3,sphere).
shape(obj4,sphere).
shape(obj5,cube).
shape(obj6,sphere).
shape(obj7,sphere).
shape(obj8,cylinder).
shape(obj9,sphere).
size(obj0,large).
size(obj1,small).
size(obj2,large).
size(obj3,large).
size(obj4,small).
size(obj5,small).
size(obj6,large).
size(obj7,large).
size(obj8,small).
size(obj9,small).
}).
#pos({kp(img)}, {}, {

color(obj0,brown).
color(obj1,gray).
color(obj2,gray).
color(obj3,gray).
color(obj4,green).
color(obj5,green).
color(obj6,gray).
color(obj7,cyan).
color(obj8,blue).
color(obj9,cyan).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,rubber).
material(obj1,rubber).
material(obj2,metal).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj6,metal).
material(obj7,metal).
material(obj8,rubber).
material(obj9,metal).
shape(obj0,cube).
shape(obj1,cube).
shape(obj2,cylinder).
shape(obj3,cube).
shape(obj4,sphere).
shape(obj5,sphere).
shape(obj7,cylinder).
shape(obj8,cube).
shape(obj9,sphere).
size(obj0,small).
size(obj1,small).
size(obj2,large).
size(obj3,large).
size(obj4,small).
size(obj5,large).
size(obj6,small).
size(obj7,small).
size(obj8,small).
size(obj9,small).
}).
#pos({kp(img)}, {}, {

color(obj0,brown).
color(obj1,yellow).
color(obj2,blue).
color(obj4,gray).
color(obj5,blue).
color(obj7,brown).
color(obj8,gray).
color(obj9,yellow).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj4,img).
in(obj5,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,metal).
material(obj1,rubber).
material(obj2,metal).
material(obj4,metal).
material(obj5,metal).
material(obj7,metal).
material(obj8,metal).
material(obj9,metal).
shape(obj0,cube).
shape(obj1,cylinder).
shape(obj2,sphere).
shape(obj4,cube).
shape(obj5,sphere).
shape(obj7,cylinder).
shape(obj8,cube).
shape(obj9,cube).
size(obj0,small).
size(obj1,large).
size(obj2,large).
size(obj4,small).
size(obj5,large).
size(obj7,small).
size(obj8,large).
size(obj9,small).
}).
#neg({kp(img)}, {}, {

color(obj0,brown).
color(obj3,gray).
color(obj4,brown).
color(obj5,gray).
color(obj8,cyan).
in(obj0,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj8,img).
material(obj0,rubber).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj8,rubber).
shape(obj0,cube).
shape(obj3,cube).
shape(obj4,sphere).
shape(obj5,cube).
shape(obj8,cube).
size(obj0,small).
size(obj3,small).
size(obj4,small).
size(obj5,small).
size(obj8,small).
}).
#neg({kp(img)}, {}, {

color(obj0,green).
color(obj1,red).
color(obj2,green).
color(obj3,gray).
color(obj6,gray).
color(obj7,red).
color(obj8,blue).
color(obj9,yellow).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj6,img).
in(obj7,img).
in(obj8,img).
in(obj9,img).
material(obj0,rubber).
material(obj1,rubber).
material(obj2,metal).
material(obj3,metal).
material(obj5,metal).
material(obj6,rubber).
material(obj7,metal).
material(obj8,metal).
material(obj9,metal).
shape(obj0,sphere).
shape(obj1,cylinder).
shape(obj2,sphere).
shape(obj3,cylinder).
shape(obj5,sphere).
shape(obj6,sphere).
shape(obj7,sphere).
shape(obj8,sphere).
shape(obj9,sphere).
size(obj0,small).
size(obj1,large).
size(obj2,large).
size(obj3,large).
size(obj4,small).
size(obj5,small).
size(obj6,small).
size(obj7,large).
size(obj8,large).
size(obj9,small).
}).
#neg({kp(img)}, {}, {

color(obj0,green).
color(obj1,red).
color(obj2,purple).
color(obj3,cyan).
color(obj4,blue).
color(obj5,brown).
color(obj7,red).
in(obj0,img).
in(obj1,img).
in(obj2,img).
in(obj3,img).
in(obj4,img).
in(obj5,img).
in(obj7,img).
material(obj0,rubber).
material(obj1,rubber).
material(obj2,metal).
material(obj3,metal).
material(obj4,metal).
material(obj5,rubber).
material(obj7,metal).
shape(obj0,cube).
shape(obj1,cube).
shape(obj2,cube).
shape(obj3,cube).
shape(obj4,cube).
shape(obj5,cube).
shape(obj7,sphere).
size(obj0,small).
size(obj1,large).
size(obj2,large).
size(obj3,large).
size(obj4,small).
size(obj5,large).
size(obj7,small).
}).
% Background Knowledge

        
% Mode Declarations
7 ~ kp(X):-in(O1,X),in(O2,X),shape(O1,cube),shape(O1,cylinder),size(O1,large),size(O2,large).
7 ~ kp(X):-in(O1,X),in(O2,X),shape(O1,cube),shape(O2,sphere),size(O1,small),size(O2,large).
7 ~ kp(X):-in(O1,X),in(O2,X),shape(O1,cylinder),shape(O2,cube),size(O1,large),size(O2,large).
7 ~ kp(X):-in(O1,X),in(O2,X),shape(O1,cylinder),shape(O2,cube),size(O1,small),size(O2,large).
6 ~ kp(X):-in(O1,X),in(O2,X),shape(O1,cylinder),shape(O2,cube),size(O2,large).
6 ~ kp(X):-in(O1,X),in(O2,X),shape(O1,cylinder),shape(O2,cylinder),size(O1,large),size(O2,large).
6 ~ kp(X):-in(O1,X),in(O2,X),shape(O1,cylinder),shape(O2,cylinder),size(O2,large).
5 ~ kp(X):-in(O1,X),in(O2,X),shape(O1,cylinder),shape(O2,sphere).
6 ~ kp(X):-in(O1,X),in(O2,X),shape(O1,cylinder),size(O1,large),size(O2,large).
6 ~ kp(X):-in(O1,X),in(O2,X),shape(O1,cylinder),size(O1,small),size(O2,large).
5 ~ kp(X):-in(O1,X),in(O2,X),shape(O1,cylinder),size(O2,large).
5 ~ kp(X):-in(O1,X),in(O2,X),shape(O1,sphere),size(O1,small).
5 ~ kp(X):-in(O1,X),in(O2,X),shape(O1,sphere),size(O2,small).
6 ~ kp(X):-in(O1,X),in(O2,X),shape(O2,sphere),size(O1,small),size(O2,large).
5 ~ kp(X):-in(O1,X),in(O2,X),shape(O2,sphere),size(O1,small).
